routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', 'ThreadController@index')->name('home');
Route::get('leaderboard', 'LeaderboardController@show');
Route::resource('/thread', 'ThreadController');

Route::middleware(['auth', 'verified'])->group(function () {
    // HALAMAN STATIS
    // Route::view('show', 'pages.show');
    // Route::view('create', 'pages.create');
    // Route::view('user/profile', 'pages.profile');

    //RESOURCES
    Route::resource('/category', 'CategoryController');
    Route::resource('/profile', 'ProfileController');

    //CRUD
    Route::post('thread/{thread}/replies', 'ThreadReplyController@store');
    Route::post('thread/{thread}/{reply}/likes', 'ReplyLikeController@store');
    Route::delete('thread/{thread}/{reply}', 'ThreadReplyController@destroy');
    Route::post('thread/{thread}/likes', 'ThreadLikeController@store');
    Route::post('thread/{thread}/spam', 'ThreadSpamController@store');
    Route::post('thread/{thread}/not-spam', 'ThreadSpamController@destroy');
    Route::post('thread/{thread}/{replies}/not-spam', 'ReplySpamController@destroy');
    Route::post('thread/{thread}/{replies}/spam', 'ReplySpamController@store');
    Route::get('replies/{reply}/edit', 'ReplyController@edit');
    Route::put('replies/{reply}', 'ReplyController@update');
    Route::post('thread/{thread}/replies/{reply}/solution', 'ThreadReplySolutionController@store');
    Route::get('notifications', 'NotificationsController@index');
    Route::post('notifications', 'NotificationsController@update');
    Route::DELETE('notifications', 'NotificationsController@destroy');
    Route::delete('replies/{reply}/{userid}', 'ReplyController@destroy');
    Route::delete('threads/{thread}/{userid}', 'ThreadController@deleteFromProfile');

});

Auth::routes();
Auth::routes(['verify' => true]);

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    const DEFAULT = 1;
    const MODERATOR = 2;
    const ADMIN = 3;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function type()
    {
        return $this->type;
    }

    public function isModerator()
    {
        return $this->type() === self::MODERATOR OR $this->type() === self::ADMIN;
    }

    public function isAdmin()
    {
        return $this->type() === self::ADMIN;
    }

    public function profile()
    {
        return $this->hasOne('App\Profile');
    }

    public function threads()
    {
        return $this->hasMany('App\Thread')->latest();
    }

    public function replies()
    {
        return $this->hasMany('App\Reply')->latest();
    }

    public function countSolutions()
    {
        return $this->replies()->isSolution()->count();
    }

    public function getProfilePhotoUrlAttribute()
    {
        return $this->photo
                    ? asset('storage/' . $this->photo)
                    : $this->defaultProfilePhotoUrl();
    }

    protected function defaultProfilePhotoUrl()
    {
        $name = trim(collect(explode(' ', $this->username))->map(function ($segment) {
            return mb_substr($segment, 0, 1);
        })->join(' '));

        return 'https://ui-avatars.com/api/?name='.urlencode($name).'&color=7F9CF5&background=EBF4FF';
    }

    protected function getNotificationsCountAttribute()
    {
        return $this->unreadNotifications()->count();
    }
}

resources/views/partials/footer.blade.php
<!-- Main Footer -->
<footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
    Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
</footer>

resources/views/partials/navbar.blade.php
<!-- Navbar -->
<nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
    <div class="container">
        <a href="{{ route('home') }}" class="navbar-brand">
            <img src="https://jabarcodingcamp.id/assets/img/Logo/LogoJCC-desktop.svg" alt="AdminLTE Logo"
                class="brand-image" style="opacity: .8">
        </a>

        <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse order-3" id="navbarCollapse">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="/leaderboard" class="nav-link">Leaderboard</a>
                </li>
            </ul>

            <!-- SEARCH FORM -->
            <form method="GET" action="/" class="form-inline ml-0 ml-md-3">
                @if (request('category'))
                    <input type="hidden" name="category" value="{{ request('category') }}">
                @endif
                <div class="input-group input-group-sm">
                    <input name="search" class="form-control form-control-navbar" type="search"
                        placeholder="Find something" aria-label="Search" value="{{ request('search') }}">
                    <div class="input-group-append">
                        <button class="btn btn-navbar" type="submit">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>


        <!-- Right navbar links -->
        <ul class="order-1 order-md-3  navbar-nav ml-auto navbar-no-expand">
            @guest
                <li class="nav-item">
                    <a class="btn btn-light px-3 mx-2 m-lg-1" href="{{ route('register') }}">
                        Register
                    </a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-info px-3 mx-2 m-lg-1" href="{{ route('login') }}">
                        Login
                    </a>
                </li>
            @else
                <li class="nav-item">
                    <a class="nav-link" href="/notifications">
                        <i class="far fa-bell"></i>
                        <span class="badge badge-warning navbar-badge">{{ ( auth()->user()->notifications_count > 9 ) ? '9+' : auth()->user()->notifications_count }}</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-light px-3 mx-2 m-lg-1" href="/profile/{{ Auth::user()->id }}">
                        <!-- Href harus menuju url profile dengan mengirimkan id user, supaya tampilan di halaman profile nanti sesuai -->
                        <img src="{{ Auth::user()->profile_photo_url }}" width="20px" class="img-circle"
                            alt="User Image">
                        <span class="ml-2">{{ Auth::user()->username }}</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-info px-3 mx-2 m-lg-1" href="{{ route('logout') }}"
                        onclick="event.preventDefault();
                                        document.getElementById('logout-form').submit();">
                        {{ __('Logout') }}
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </li>
            @endguest
        </ul>
    </div>
</nav>
<!-- /.navbar -->

resources/views/partials/sidebar.blade.php
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{{ route('home') }}" class="brand-link">
      <img src="{{ asset('dist/img/AdminLTELogo.png') }}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="pb-3 mt-3 mb-3 user-panel d-flex">
        <div class="image">
          <img src="{{ asset('dist/img/user2-160x160.jpg') }}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">Dede Iskandar</a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
            <li class="nav-item">
                <a href="/" class="nav-link {{ request()->is('/') ? 'active' : '' }}">
                    <i class="nav-icon fas fa-tachometer-alt"></i>
                    <p>
                        Dashboard
                    </p>
                </a>
            </li>
            <li class="nav-item">
                <a href="/cast" class="nav-link {{ request()->is('cast') ? 'active' : '' }}">
                    <i class="nav-icon fas fa-user"></i>
                    <p>
                        Cast
                    </p>
                </a>
            </li>
            {{-- <li class="nav-item {{ request()->is('*table*') ? 'menu-open' : '' }}">
                <a href="#" class="nav-link {{ request()->is('*table*') ? 'active' : '' }}">
                    <i class="nav-icon fas fa-table"></i>
                    <p>
                        Tables
                        <i class="right fas fa-angle-left"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a href="{{ route('table') }}" class="nav-link {{ request()->is('table') ? 'active' : '' }}">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Table</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('data-tables') }}" class="nav-link {{ request()->is('data-tables') ? 'active' : '' }}">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Data Tables</p>
                    </a>
                </li>
                </ul>
            </li> --}}

        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>