routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', 'ThreadController@index')->name('home');
Route::get('leaderboard', 'LeaderboardController@show');
Route::resource('/thread', 'ThreadController');

Route::middleware(['auth', 'verified'])->group(function () {
    // HALAMAN STATIS
    // Route::view('show', 'pages.show');
    // Route::view('create', 'pages.create');
    // Route::view('user/profile', 'pages.profile');

    //RESOURCES
    Route::resource('/category', 'CategoryController');
    Route::resource('/profile', 'ProfileController');

    //CRUD
    Route::post('thread/{thread}/replies', 'ThreadReplyController@store');
    Route::post('thread/{thread}/{reply}/likes', 'ReplyLikeController@store');
    Route::delete('thread/{thread}/{reply}', 'ThreadReplyController@destroy');
    Route::post('thread/{thread}/likes', 'ThreadLikeController@store');
    Route::post('thread/{thread}/spam', 'ThreadSpamController@store');
    Route::post('thread/{thread}/not-spam', 'ThreadSpamController@destroy');
    Route::post('thread/{thread}/{replies}/not-spam', 'ReplySpamController@destroy');
    Route::post('thread/{thread}/{replies}/spam', 'ReplySpamController@store');
    Route::get('replies/{reply}/edit', 'ReplyController@edit');
    Route::put('replies/{reply}', 'ReplyController@update');
    Route::post('thread/{thread}/replies/{reply}/solution', 'ThreadReplySolutionController@store');
    Route::get('notifications', 'NotificationsController@index');
    Route::post('notifications', 'NotificationsController@update');
    Route::DELETE('notifications', 'NotificationsController@destroy');
    Route::delete('replies/{reply}/{userid}', 'ReplyController@destroy');
    Route::delete('threads/{thread}/{userid}', 'ThreadController@deleteFromProfile');

});

Auth::routes();
Auth::routes(['verify' => true]);

app/Thread.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Thread extends Model
{
    protected $table = 'threads';

    protected $fillable = [
        'user_id',
        'category_id',
        'slug',
        'subject',
        'body',
        'thumbnail',
        'views_count',
        'spam_reports',
        'solution_reply_id'
    ];

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function excerpt(int $limit = 265): string
    {
        return Str::limit(strip_tags($this->body), $limit);
    }

    public function creator()
    {
        return $this->belongsTo('App\User', 'user_id');
    }

    public function replies()
    {
        return $this->hasMany('App\Reply');
    }

    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function like($user= null)
    {
        $user = $user ?: auth()->user();

        return $this->isLikedBy(auth()->user()) ? $this->likes()->detach($user) : $this->likes()->attach($user);
    }

    public function likes()
    {
        return $this->morphToMany('App\User', 'likable')->withTimestamps();
    }

    public function isLikedBy(User $user)
    {
        return $this->likes()->where('user_id', $user->id)->exists();
    }

    public function isSolved()
    {
        return null !== $this->solution_reply_id;
    }

    public function isUpdated()
    {
        return $this->updated_at->gt($this->created_at);
    }

    public function scopeFilter($query, array $filters)
    {
        $query->when($filters['search'] ?? false, function ($query, $search) {
            $query->where(function($query) use ($search) {
                $query->where('subject', 'like', '%' . $search . '%')
                    ->orWhere('body', 'like', '%' . $search . '%');
            });
        });

        $query->when($filters['category'] ?? false, function ($query, $category) {
            $query->whereHas('category', function ($query) use ($category) {
                $query->where('slug', $category);
            });
        });

        $query->when($filters['author'] ?? false, function ($query, $author) {
            $query->where('user_id', $author);
        });

        $query->when(\Request::has('spam') && \Request::query('spam') == 'threads' ?? false, function ($query) {
            $query->orderBy('spam_reports', 'DESC');
        });

        $query->when(\Request::has('popular') && \Request::query('popular') == 'views' ?? false, function ($query) {
            $query->orderBy('views_count', 'DESC');
        });

        $query->when(\Request::has('popular') && \Request::query('popular') == 'likes' ?? false, function($query) {
            $query->orderBy('likes_count', 'DESC');
        });

        $query->when(\Request::has('popular') && \Request::query('popular') == 'replies' ?? false, function($query) {
            $query->orderBy('replies_count', 'DESC');
        });
    }

    public function getThumbnailUrlAttribute()
    {
        return $this->thumbnail
                    ? asset($this->thumbnail)
                    : asset('images/thumbnail-placeholder.svg');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    const DEFAULT = 1;
    const MODERATOR = 2;
    const ADMIN = 3;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function type()
    {
        return $this->type;
    }

    public function isModerator()
    {
        return $this->type() === self::MODERATOR OR $this->type() === self::ADMIN;
    }

    public function isAdmin()
    {
        return $this->type() === self::ADMIN;
    }

    public function profile()
    {
        return $this->hasOne('App\Profile');
    }

    public function threads()
    {
        return $this->hasMany('App\Thread')->latest();
    }

    public function replies()
    {
        return $this->hasMany('App\Reply')->latest();
    }

    public function countSolutions()
    {
        return $this->replies()->isSolution()->count();
    }

    public function getProfilePhotoUrlAttribute()
    {
        return $this->photo
                    ? asset('storage/' . $this->photo)
                    : $this->defaultProfilePhotoUrl();
    }

    protected function defaultProfilePhotoUrl()
    {
        $name = trim(collect(explode(' ', $this->username))->map(function ($segment) {
            return mb_substr($segment, 0, 1);
        })->join(' '));

        return 'https://ui-avatars.com/api/?name='.urlencode($name).'&color=7F9CF5&background=EBF4FF';
    }

    protected function getNotificationsCountAttribute()
    {
        return $this->unreadNotifications()->count();
    }
}

app/Http/Controllers/ThreadController.php
<?php

namespace App\Http\Controllers;

use App\Thread;
use App\User;
use App\Profile;
use App\Reply;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use RealRashid\SweetAlert\Facades\Alert;

class ThreadController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['thread_count'] = DB::table('threads')->count();

        $threads = Thread::query()
            ->with('category:id,slug,name')
            ->withCount('replies','likes')
            ->filter(
                request(['search', 'author', 'category', 'popular', 'spam'])
            )
            ->latest()
            ->simplePaginate(5);

        return view('thread.index', [
            'data' => $data,
            'threads' => $threads,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if( ! Auth::check())
        {
            return redirect()->route('login');
        }
        return view('thread.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'subject' => 'required',
            'body' => 'required',
            'category_id' => 'required',
            'thumbnail' => 'nullable|mimes:png,jpg,jpeg|max:1024',
        ]);

        $thread = Thread::create([
            'user_id' => auth()->id(),
            'subject' => $validated['subject'],
            'body' => $validated['body'],
            'category_id' => $validated['category_id'],
            'slug' => Str::slug($validated['subject'], '-'),
        ]);

        if($request->hasFile('thumbnail'))
        {
            $thumbnail = $request->thumbnail;
            $file_name = time().'-'.$thumbnail->getClientOriginalName();
            $thumbnail->move('images/thumbnail/', $file_name);
            $thread->update([
                'thumbnail' => 'images/thumbnail/' . $file_name,
            ]);
        }

        Alert::success('Success', 'New Discussion has been created');

        return redirect()->route('thread.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Thread $thread)
    {
        $thread->update([
            'views_count' => $thread->views_count + 1
        ]);

        return view('thread.show', [
            'thread' => $thread
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Thread $thread)
    {
        return view('thread.edit', [
            'thread' => $thread
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Thread $thread)
    {
        $validated = $request->validate([
            'subject' => 'required',
            'body' => 'required',
            'category_id' => 'required',
            'thumbnail' => 'nullable|mimes:png,jpg,jpeg|max:1024',
        ]);

        $thread->update([
            'user_id' => auth()->id(),
            'subject' => $validated['subject'],
            'body' => $validated['body'],
            'category_id' => $validated['category_id'],
            'slug' => Str::slug($validated['subject'], '-'),
        ]);

        if($request->hasFile('thumbnail'))
        {
            File::delete($thread->thumbnail);
            $thumbnail = $request->thumbnail;
            $file_name = time().'-'.$thumbnail->getClientOriginalName();
            $thumbnail->move('images/thumbnail/', $file_name);
            $thread->update([
                'thumbnail' => 'images/thumbnail/' . $file_name,
            ]);
        }

        Alert::success('Update', 'Thread has been updated');

        return redirect()->route('thread.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Thread $thread)
    {
        $thread->delete();
        Alert::success('Deleted', 'Thread has been deleted');

        return redirect()->route('thread.index');
    }

    public function deleteFromProfile($id, $user_id)
    {
        $thread = Thread::find($id);
        $thread->delete();
        Alert::success('Deleted', 'Thread has been deleted');

        $users = User::findOrFail($user_id);
        $user = Profile::where('user_id', '=', $user_id)->first();
        $threads = Thread::query()->withCount('replies','likes')->where('user_id', '=', $user_id)->get();
        $replies = Reply::query()->withCount('likes')->where('user_id', '=', $user_id)->get();

        return redirect()->route('profile.show', $user_id);
    }
}

resources/views/thread/create.blade.php
@extends('layouts.master')

@section('content-header')
<h1 class="font-weight-bold my-3">Create a new thread</h1>
@endsection

@section('main-content')

<div class="row ">
    <div class="col mb-3">
        <form action="/thread" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="subject">Subject</label>
                <input name="subject" value="{{ old('subject' )}}" type="text" class="form-control @error('subject') is-invalid @enderror " id="subject" placeholder="Enter Subject" >
                @error('subject')
                <div class="invalid-feedback">
                    {{ $message }}
                </div>
                @enderror
            </div>
            <div class="form-group">
                <label>Category</label>
                <select name="category_id" class="form-control">
                    <option value="">Pilih salah satu</option>
                    @foreach (\DB::table('categories')->get(['id', 'name']) as $category)
                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                    @endforeach
                </select>
                @error('category_id')
                <div class="invalid-feedback">
                    {{ $message }}
                </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="thumbnail">Thumbnail</label>
                <div class="input-group">
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" name="thumbnail" id="thumbnail">
                        <label class="custom-file-label" for="thumbnail">Choose file</label>
                    </div>
                    <div class="input-group-append">
                        <span class="input-group-text">Upload</span>
                    </div>
                </div>
                @error('thumbnail')
                <div class="invalid-feedback">
                    {{ $message }}
                </div>
                @enderror
            </div>
            <div class="form-group">
                <label>Body</label>
                <textarea id="summernote" name="body">{{ old('body' )}}</textarea>
            </div>
            @error('body')
                <div class="invalid-feedback">
                    {{ $message }}
                </div>
            @enderror
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>

@endsection

@push('styles')
<!-- summernote -->
<link rel="stylesheet" href="{{ asset('plugins/summernote/summernote-bs4.min.css') }}">

<style>
    .note-toolbar {
        background: white;
    }
</style>
@endpush

@push('scripts')
<!-- Summernote -->
<script src="{{ asset('plugins/summernote/summernote-bs4.min.js') }}"></script>
<!-- bs-custom-file-input -->
<script src="{{ asset('plugins/bs-custom-file-input/bs-custom-file-input.min.js') }}"></script>

<script>
    $(function () {
        // Summernote
        $('#summernote').summernote({
            toolbar: [
                ['style', ['style']],
                ['font', ['bold', 'underline', 'clear']],
                ['fontname', ['fontname']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['insert', ['link']],
                ['view', ['fullscreen', 'codeview', 'help']],
            ]
        });

        bsCustomFileInput.init();
    })
  </script>
@endpush

resources/views/thread/edit.blade.php
@extends('layouts.master')

@section('content-header')
<h1 class="font-weight-bold my-3">Create a new thread</h1>
@endsection

@section('main-content')

<div class="row ">
    <div class="col mb-3">
        <form action="/thread/{{ $thread->slug }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('put')
            <div class="form-group">
                <label for="subject">Subject</label>
                <input name="subject" value="{{ $thread->subject }}" type="text" class="form-control @error('subject') is-invalid @enderror " id="subject" placeholder="Enter Subject" >
                @error('subject')
                <div class="invalid-feedback">
                    {{ $message }}
                </div>
                @enderror
            </div>
            <div class="form-group">
                <label>Category</label>
                <select name="category_id" class="form-control">
                    <option value="">Pilih salah satu</option>
                    @foreach (\DB::table('categories')->get(['id', 'name']) as $category)
                    <option @if ($thread->category_id == $category->id) selected @endif value="{{ $category->id }}">{{ $category->name }}</option>
                    @endforeach
                </select>
                @error('category_id')
                <div class="invalid-feedback">
                    {{ $message }}
                </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="thumbnail">Thumbnail</label>
                <div class="input-group">
                    <div class="custom-file">
                        <input name="thumbnail" type="file" class="custom-file-input" id="thumbnail">
                        <label class="custom-file-label" for="image">Choose file</label>
                    </div>
                    <div class="input-group-append">
                        <span class="input-group-text">Upload</span>
                    </div>
                </div>
                @error('thumbnail')
                <div class="invalid-feedback">
                    {{ $message }}
                </div>
                @enderror
            </div>
            <div class="form-group">
                <label>Body</label>
                <textarea id="summernote" name="body">{{ $thread->body }}</textarea>
            </div>
            @error('body')
                <div class="invalid-feedback">
                    {{ $message }}
                </div>
            @enderror
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>

@endsection

@push('styles')
<!-- summernote -->
<link rel="stylesheet" href="{{ asset('plugins/summernote/summernote-bs4.min.css') }}">

<style>
    .note-toolbar {
        background: white;
    }
</style>
@endpush

@push('scripts')
<!-- Summernote -->
<script src="{{ asset('plugins/summernote/summernote-bs4.min.js') }}"></script>
<!-- bs-custom-file-input -->
<script src="{{ asset('plugins/bs-custom-file-input/bs-custom-file-input.min.js') }}"></script>

<script>
    $(function () {
        $('#summernote').summernote({
            toolbar: [
                ['style', ['style']],
                ['font', ['bold', 'underline', 'clear']],
                ['fontname', ['fontname']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['insert', ['link']],
                ['view', ['fullscreen', 'codeview', 'help']],
            ]
        });

        bsCustomFileInput.init();
    })
  </script>
@endpush

resources/views/thread/index.blade.php
@extends('layouts.master')

@section('content-header')
<div class="d-flex mb-3 justify-content-between">
    <h1 class="font-weight-bold">Forum</h1>
    <div>
        @auth
            @if (auth()->user()->isAdmin())
                <a href="{{ route('category.index') }}" class="btn btn-danger">Categories</a>
            @endif
        @endauth
        <a href="{{ route('thread.create') }}" class="btn btn-primary">New Discussion</a>
    </div>
</div>

<div class="row">
    <div class="col-sm-6">
        <h5>{{ $data['thread_count'] }} diskusi</h5>
    </div><!-- /.col -->
    <div class="col-sm-6 ">
        <div class="form-row">
            <div class="col">
                <select class="form-control" onchange="location = this.value">
                    <option value="/?{{ http_build_query(request()->except('page', 'popular', 'author')) }}">Latest</option>
                    <option @if (\Request::has('popular') && (\Request::query('popular') == 'views')) selected @endif value="/?{{ http_build_query(request()->except('page', 'spam', 'author', 'popular')) }}&popular=views">Top Views</option>
                    <option @if (\Request::has('popular') && (\Request::query('popular') == 'likes')) selected @endif value="/?{{ http_build_query(request()->except('page', 'spam', 'author', 'popular')) }}&popular=likes">Top Likes</option>
                    <option @if (\Request::has('popular') && (\Request::query('popular') == 'replies')) selected @endif value="/?{{ http_build_query(request()->except('popular', 'page', 'spam', 'author',)) }}&popular=replies">Top Replies</option>
                    @auth
                        <option @if (\Request::has('author')) selected @endif value="/?{{ http_build_query(request()->except('page', 'popular')) }}&author={{ Auth()->id() }}">My Threads</option>
                        @if (auth()->user()->isModerator())
                            <option @if (\Request::has('spam') && (\Request::query('spam') == 'threads'))  selected @endif value="/?{{ http_build_query(request()->except('page', 'popular', 'author')) }}&spam=threads">Spam Reports</option>
                        @endif
                    @endauth
                </select>
            </div>
            <div class="col">
                <select class="form-control" onchange="location = this.value">
                    <option value="?">Semua Category</option>
                    @foreach (\DB::table('categories')->get(['slug', 'name']) as $category)
                    <option @if (\Request::has('category') && (\Request::query('category') == $category->slug) ) selected @endif value="/?category={{ $category->slug }}&{{ http_build_query(request()->except('category', 'page')) }}">{{ $category->name }}</option>
                    @endforeach
                </select>
            </div>
        </div>
    </div><!-- /.col -->
</div><!-- /.row -->
@endsection

@section('main-content')
<div class="row">
    <div class="col">
        @forelse ($threads as $thread)
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-auto d-none d-sm-block">
                        <img class="img-thumbnail" alt="200x200" src="{{ asset($thread->thumbnail_url) }}" style="width: 170px;  height: 170px;">
                    </div>
                    <div class="col">
                        <div class="d-flex mb-2 justify-content-between">
                            <div class="d-sm-flex justify-items-center">
                                <div class="d-flex justify-items-center">
                                    <img src="{{ $thread->creator->profile_photo_url }}" width="25px" height="25px" class="img-circle" alt="User Image">
                                    <a href="/profile/{{ $thread->creator->id }}" class="ml-2 font-weight-bold ">{{ $thread->creator->username }}</a>
                                </div>
                                <div class="sm-ml-2 text-muted">{{ $thread->created_at->diffForHumans() }}</div>
                            </div>
                            <div class="d-flex align-items-center">
                                <a href="/?category={{ $thread->category->slug }}" class="btn px-2 btn-xs btn-outline-warning">{{ $thread->category->name }}</a>
                            </div>
                        </div>

                        @auth
                            @if (auth()->user()->isModerator() && $thread->spam_reports > 0)
                                <div class="mb-1 text-danger">spam reported : {{ $thread->spam_reports }}</div>
                            @endif
                        @endauth
                        <h4 class="font-weight-bold">
                            <a href="{{ route('thread.show', $thread->slug) }}">
                                {{ $thread->subject }}
                            </a>
                        </h4>
                        <p class="card-text">
                            {{ $thread->excerpt() }}
                        </p>
                        <div class="d-flex justify-content-between">
                            <div class="d-flex align-content-middle">
                                <div class="card-link text-secondary">
                                    <form method="POST"
                                        action="/thread/{{ $thread->slug }}/likes"
                                    >
                                        @csrf

                                        <button type="submit" class="display-button @if (Auth::check() && $thread->isLikedBy(auth()->user())) text-success @else text-secondary @endif ">
                                            <i class="far fa-thumbs-up "></i><span class="ml-1 ">{{ $thread->likes->count() }}</span>
                                        </button>
                                    </form>
                                </div>
                                <span class="card-link text-secondary"><i class="far fa-comments"></i> <span class="ml-1">{{ $thread->replies_count }}</span></span>
                                <span class="card-link text-secondary"><i class="far fa-eye"></i> <span class="ml-1">{{ $thread->views_count }}</span></span>
                                @if ($thread->isSolved())
                                <span class="text-success ml-4"><i class="fa fa-check"></i>
                                    Solved
                                </span>
                                @endif
                            </div>
                            <div >
                                @if (Auth::check() && (auth()->user()->isModerator() OR auth()->id() == $thread->user_id) )
                                    <div class="dropdown ml-4">
                                        <button class="btn btn-sm btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            Action
                                        </button>
                                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                                            @if (auth()->id() == $thread->user_id)
                                                <a class="dropdown-item" href="{{ route('thread.edit', $thread->slug) }}">Edit</a>
                                            @endif
                                            @if (auth()->id() == $thread->user_id OR auth()->user()->isModerator())
                                            <form action="/thread/{{ $thread->slug }}" method="post">
                                                @csrf
                                                @method('delete')
                                                <input
                                                type="submit"
                                                    class="dropdown-item"
                                                    value="Delete"
                                                    onclick="return confirm('Are you sure you want to delete?');"
                                                    >
                                            </form>
                                            @endif
                                            @if (auth()->user()->isModerator())
                                            <form action="/thread/{{ $thread->slug }}/spam" method="POST">
                                                @csrf
                                                <input
                                                    type="submit"
                                                    class="dropdown-item"
                                                    value="Mark as Spam"
                                                    onclick="return confirm('Are you sure you want to report spam this thread?');"
                                                >
                                            </form>
                                            <form action="/thread/{{ $thread->slug }}/not-spam" method="POST">
                                                @csrf
                                                <input
                                                    type="submit"
                                                    class="dropdown-item"
                                                    value="Not Spam"
                                                    onclick="return confirm('Are you sure you want to mark this idea as NOT spam? This will reset the spam counter to 0.');"
                                                >
                                            </form>
                                            @endif
                                        </div>
                                    </div>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @empty
            <p class="text-center my-5 h4 font-weight-bold">No Thread yet. Please check back later.</p>
        @endforelse

        @isset ($threads)
        <div class="d-flex justify-content-center">
            {{ $threads->appends('category', \Request::query('category'))->links() }}
        </div>
        @endisset
    </div>
</div>

@endsection

@push('styles')
    <style>
        .display-button {
            border:0;
            outline:0;
            background: none;
        }
        .display-button:focus {
            outline:none!important;
        }
    </style>
@endpush

@push('scripts')
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
@endpush